import 'package:fitness_application/models/workout.dart';

List<Workout> get workouts {
  return [
    // TODO: Custom program
    // Warm Up
    Workout(
      sysId: 'WRKT0',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE1',
      day: 1,
      reps: 20,
      type: WorkoutType.warmUp,
      restTime: 304,
    ),
    Workout(
      sysId: 'WRKT1',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE2',
      prevWorkoutSysId: 'WRKT0',
      day: 1,
      reps: 20,
      type: WorkoutType.warmUp,
      restTime: 450,
    ),

    // Workout
    Workout(
      sysId: 'WRKT2',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE3',
      prevWorkoutSysId: 'WRKT1',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 70,
    ),
    Workout(
      sysId: 'WRKT3',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE4',
      prevWorkoutSysId: 'WRKT2',
      day: 1,
      time: 300,
      type: WorkoutType.workout,
      restTime: 40,
    ),
    Workout(
      sysId: 'WRKT4',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE5',
      prevWorkoutSysId: 'WRKT3',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 10,
    ),
    Workout(
      sysId: 'WRKT5',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE1',
      prevWorkoutSysId: 'WRKT4',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 50,
    ),
    Workout(
      sysId: 'WRKT6',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE2',
      prevWorkoutSysId: 'WRKT5',
      day: 1,
      time: 150,
      type: WorkoutType.workout,
      restTime: 3,
    ),

    // Cool down
    Workout(
      sysId: 'WRKT7',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE3',
      prevWorkoutSysId: 'WRKT6',
      day: 1,
      reps: 20,
      type: WorkoutType.coolDown,
      restTime: 20,
    ),
    Workout(
      sysId: 'WRKT8',
      programSysId: 'CTPR',
      exerciseSysId: 'EXE4',
      prevWorkoutSysId: 'WRKT7',
      day: 1,
      reps: 20,
      type: WorkoutType.coolDown,
    ),

    // TODO: Program 1
    // Warm Up
    Workout(
      sysId: 'WRKT9',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE5',
      day: 1,
      reps: 25,
      type: WorkoutType.warmUp,
      restTime: 90,
    ),
    Workout(
      sysId: 'WRKT10',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE1',
      prevWorkoutSysId: 'WRKT9',
      day: 1,
      reps: 20,
      type: WorkoutType.warmUp,
      restTime: 70,
    ),

    // Workout
    Workout(
      sysId: 'WRKT11',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE2',
      prevWorkoutSysId: 'WRKT10',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 18,
    ),
    Workout(
      sysId: 'WRKT12',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE3',
      prevWorkoutSysId: 'WRKT11',
      day: 1,
      time: 300,
      type: WorkoutType.workout,
      restTime: 41,
    ),
    Workout(
      sysId: 'WRKT13',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE4',
      prevWorkoutSysId: 'WRKT12',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 325,
    ),
    Workout(
      sysId: 'WRKT14',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE5',
      prevWorkoutSysId: 'WRKT13',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 40,
    ),
    Workout(
      sysId: 'WRKT15',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE1',
      prevWorkoutSysId: 'WRKT14',
      day: 1,
      time: 150,
      type: WorkoutType.workout,
      restTime: 10,
    ),

    // Cool down
    Workout(
      sysId: 'WRKT16',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE2',
      prevWorkoutSysId: 'WRKT15',
      day: 1,
      reps: 20,
      type: WorkoutType.coolDown,
      restTime: 300,
    ),
    Workout(
      sysId: 'WRKT17',
      programSysId: 'PROG1',
      exerciseSysId: 'EXE3',
      prevWorkoutSysId: 'WRKT16',
      day: 1,
      reps: 20,
      type: WorkoutType.coolDown,
    ),

    // TODO: Program 2
    // Warm Up
    Workout(
      sysId: 'WRKT18',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE4',
      day: 1,
      reps: 25,
      type: WorkoutType.warmUp,
      restTime: 0,
    ),
    Workout(
      sysId: 'WRKT19',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE5',
      prevWorkoutSysId: 'WRKT18',
      day: 1,
      reps: 20,
      type: WorkoutType.warmUp,
      restTime: 0,
    ),

    // Workout
    Workout(
      sysId: 'WRKT20',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE1',
      prevWorkoutSysId: 'WRKT19',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 130,
    ),
    Workout(
      sysId: 'WRKT21',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE2',
      prevWorkoutSysId: 'WRKT20',
      day: 1,
      time: 300,
      type: WorkoutType.workout,
      restTime: 230,
    ),
    Workout(
      sysId: 'WRKT22',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE3',
      prevWorkoutSysId: 'WRKT21',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 430,
    ),
    Workout(
      sysId: 'WRKT23',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE4',
      prevWorkoutSysId: 'WRKT22',
      day: 1,
      reps: 20,
      type: WorkoutType.workout,
      restTime: 930,
    ),
    Workout(
      sysId: 'WRKT24',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE5',
      prevWorkoutSysId: 'WRKT23',
      day: 1,
      time: 150,
      type: WorkoutType.workout,
      restTime: 730,
    ),

    // Cool down
    Workout(
      sysId: 'WRKT25',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE1',
      prevWorkoutSysId: 'WRKT24',
      day: 1,
      reps: 20,
      type: WorkoutType.coolDown,
      restTime: 630,
    ),
    Workout(
      sysId: 'WRKT26',
      programSysId: 'PROG0',
      exerciseSysId: 'EXE2',
      prevWorkoutSysId: 'WRKT25',
      day: 1,
      reps: 20,
      type: WorkoutType.coolDown,
    ),
  ];
}
